In [9]:
print("hello")

hello

In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [11]:
df = pd.read_csv('../data/SalesData.csv')
df.head()

,Order_ID,Customer_ID,Date,Age,Gender,City,Product_Category,Unit_Price,Quantity,Discount_Amount,...,Avg_Item_Price,Discount_Percentage,Cost_Price,Profit,Profit_Margin,Cart_Size,Engagement_Score,Pages_Per_Minute,Is_Delayed,Rating_Category
0,ORD_000001-1,CUST_00001,2023-05-28,40,Male,Delhi (NCR),Books,29.18,1,0.00,...,29.18,0.000000,20.426,8.754,0.300000,1,126,0.642857,1,Medium
1,ORD_000001-2,CUST_00001,2023-10-12,40,Male,Delhi (NCR),Home & Garden,644.40,1,138.05,...,506.35,0.214230,451.080,55.270,0.109154,1,112,0.571429,0,Low
2,ORD_000001-3,CUST_00001,2023-12-05,40,Male,Delhi (NCR),Sports,332.82,5,0.00,...,332.82,0.000000,232.974,1431.126,0.860000,5,150,0.666667,1,Medium
3,ORD_000002-1,CUST_00002,2023-05-11,33,Male,Bengaluru,Food,69.30,5,71.05,...,55.09,0.205051,48.510,226.940,0.823888,5,208,0.812500,0,Medium
4,ORD_000002-2,CUST_00002,2023-06-16,33,Male,Bengaluru,Beauty,178.15,3,0.00,...,178.15,0.000000,124.705,409.745,0.766667,3,98,0.500000,0,Medium

In [12]:
df.shape

(17049, 29)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17049 entries, 0 to 17048
Data columns (total 29 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Order_ID                  17049 non-null  object
 1   Customer_ID               17049 non-null  object
 2   Date                      17049 non-null  object
 3   Age                       17049 non-null  int64
 4   Gender                    17049 non-null  object
 5   City                      17049 non-null  object
 6   Product_Category          17049 non-null  object
 7   Unit_Price                17049 non-null  float64
 8   Quantity                  17049 non-null  int64
 9   Discount_Amount           17049 non-null  float64
 10  Total_Amount              17049 non-null  float64
 11  Payment_Method            17049 non-null  object
 12  Device_Type               17049 non-null  object
 13  Session_Duration_Minutes  17049 non-null  int64
 14  Pages_Viewed              17049 non-null  int64
 15  Is_Returning_Customer     17049 non-null  bool
 16  Delivery_Time_Days        17049 non-null  int64
 17  Customer_Rating           17049 non-null  int64
 18  Total_Sales               17049 non-null  float64
 19  Avg_Item_Price            17049 non-null  float64
 20  Discount_Percentage       17049 non-null  float64
 21  Cost_Price                17049 non-null  float64
 22  Profit                    17049 non-null  float64
 23  Profit_Margin             17049 non-null  float64
 24  Cart_Size                 17049 non-null  int64
 25  Engagement_Score          17049 non-null  int64
 26  Pages_Per_Minute          17049 non-null  float64
 27  Is_Delayed                17049 non-null  int64
 28  Rating_Category           17049 non-null  object
dtypes: bool(1), float64(10), int64(9), object(9)
memory usage: 3.7+ MB

In [14]:
df.describe()

,Age,Unit_Price,Quantity,Discount_Amount,Total_Amount,Session_Duration_Minutes,Pages_Viewed,Delivery_Time_Days,Customer_Rating,Total_Sales,Avg_Item_Price,Discount_Percentage,Cost_Price,Profit,Profit_Margin,Cart_Size,Engagement_Score,Pages_Per_Minute,Is_Delayed
count,17049.000000,17049.000000,17049.000000,17049.000000,17049.000000,17049.000000,17049.000000,17049.000000,17049.000000,17049.000000,17049.000000,17049.000000,17049.000000,17049.000000,17049.000000,17049.000000,17049.000000,17049.000000,17049.000000
mean,34.945745,447.901689,3.011379,69.788135,1277.438711,14.535633,9.003109,6.503607,3.899408,1277.438711,424.242963,0.051380,313.531182,963.907529,0.661804,3.011379,130.917884,0.648041,0.322365
std,11.046855,722.319705,1.417027,240.704662,2358.436375,2.925524,2.259954,3.488787,1.128803,2358.436375,684.905308,0.072353,505.623794,1936.998301,0.218418,1.417027,42.788765,0.224666,0.467396
min,18.000000,5.050000,1.000000,0.000000,6.210000,4.000000,1.000000,1.000000,1.000000,6.210000,4.380000,0.000000,3.535000,1.077000,0.102724,1.000000,10.000000,0.062500,0.000000
25%,26.000000,73.260000,2.000000,0.000000,172.970000,13.000000,7.000000,4.000000,3.000000,172.970000,69.470000,0.000000,51.282000,99.697000,0.608243,2.000000,99.000000,0.500000,0.000000
50%,35.000000,174.680000,3.000000,0.000000,455.850000,15.000000,9.000000,6.000000,4.000000,455.850000,165.430000,0.000000,122.276000,300.351000,0.766667,3.000000,128.000000,0.619048,0.000000
75%,42.000000,494.570000,4.000000,32.710000,1267.750000,17.000000,11.000000,8.000000,5.000000,1267.750000,468.220000,0.107851,346.199000,909.744000,0.825000,4.000000,156.000000,0.769231,1.000000
max,75.000000,7900.010000,5.000000,6538.290000,37852.050000,26.000000,18.000000,25.000000,5.000000,37852.050000,7570.410000,0.220002,5530.007000,32552.763000,0.860000,5.000000,352.000000,3.500000,1.000000

In [15]:
df['City'].value_counts()

City
Bengaluru      4402
Delhi (NCR)    2422
Mumbai         2072
Hyderabad      1721
Pune           1326
Chennai        1246
Kolkata        1183
Ahmedabad      1120
Lucknow         851
Jaipur          706
Name: count, dtype: int64